on:
  push:
    branches:
      - 'release_*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install pnpm 6.32.4
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.4

      - name: Set node version to 16.14
        uses: actions/setup-node@v2
        with:
          node-version: 16.14
          cache: 'pnpm'

      - name: Get cached dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --shamefully-hoist

      - name: Run linter
        run: pnpm lint

      - name: Test
        run: pnpm typecheck

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
        
      - name: deploy
        uses: appleboy/scp-action@master
        with: 
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USER}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: 22
          source: ".output/"
          target: ${{secrets.SERVER_TARGET}}
